# fly.toml app configuration file generated for export-libib-checkout on 2025-02-09T23:27:08+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'export-libib-checkout'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "csv_data"
  destination = "/app/downloads"
